# https://rpubs.com/subasish/191372
# https://cran.r-project.org/web/packages/stm/stm.pdf
# https://stackoverflow.com/questions/52471518/how-to-get-exact-relative-topic-prevalence-out-of-stm-over-multiple-time-period
# to make the ggplot prettier: http://r-statistics.co/Top50-Ggplot2-Visualizations-MasterList-R-Code.html

library(stm)
library("ggplot2")
library(gridExtra)
library(tidytext)
library(tidystm)
library(quanteda)
library(tidyverse)
library(stringr)
library(igraph)
library(drlib)

###############################################################################################
#---------Data import & preprocessing----------------------------------------------------------
###############################################################################################

data <- read.csv("applebee_tweets_cleaned.csv")

#----------------------------------------------------------------------------------------------
processed <- textProcessor(data$documents, metadata = data, stem = FALSE, 
                           removestopwords = TRUE, customstopwords = TRUE,
                           sparselevel = 1)

# Prepare: Associating text with metadata
# -- can change the threshold values "lower.thresh = 20"
#----------------------------------------------------------------------------------------------
plotRemoved(processed$documents, lower.thresh = seq(1, 200, by = 100))
# out: document-term matrix (Document-term matrix representation of the raw documents, 
# as generated by the prepDocuments function)
out <- prepDocuments(processed$documents, processed$vocab, 
                     processed$meta, lower.thresh = 20)
set.seed(02138)
#----------------------------------------------------------------------------------------------
docs <- out$documents
vocab <- out$vocab
meta <-out$meta
#write.csv(meta, "applebee_meta_processeddata.csv")


###############################################################################################
#-----------------Model building--------------------------------------------------------------
###############################################################################################

# Estimation with topical prevalence parameter
poliblogPrevFit <- stm(out$documents, out$vocab, K = 50, 
                       prevalence =~ apple + retweet_1 + marketing, 
                       max.em.its = 200, data = out$meta, init.type = "Spectral", 
                       seed = 8458159)

#----------------------------------------------------------------------------------------------

# theta 
theta <- poliblogPrevFit$theta
#write.csv(poliblogPrevFit$theta, "applebee_50_theta.csv")
#----------------------------------------------------------------------------------------------
# Beta
checkBeta(poliblogPrevFit)
td_beta <- tidy(poliblogPrevFit)
# Beta: CSV
#write.csv(td_beta, "beta.csv")
#----------------------------------------------------------------------------------------------
# Beta: visualize
# make ggplot pretty: https://stackoverflow.com/questions/34522732/changing-fonts-in-ggplot2
#td_beta_plot <- td_beta %>% 
td_beta %>% 
  group_by(topic) %>%
  top_n(10, beta) %>%
  ungroup() %>%
  mutate(topic = paste0("Topic ", topic),
         term = reorder_within(term, beta, topic)) %>%
  ggplot(aes(term, beta, fill = as.factor(topic))) +
  geom_col(alpha = 0.8, show.legend = FALSE) +
  facet_wrap(~ topic, scales = "free_y") +
  coord_flip() +
  scale_x_reordered() +
  theme(text=element_text(size=5, family="Bahnschrift"), legend.position = "bottom") +
  labs(x = NULL, y = expression(beta),
       title = "Highest word probabilities for each topic",
       subtitle = "Different words are associated with different topics")
#ggsave("td_beta.png", plot = td_beta_plot, width = 30, height = 20, units = "cm")
#----------------------------------------------------------------------------------------------
# Gamma
td_gamma <- tidy(poliblogPrevFit, matrix = "gamma")
ggplot(td_gamma, aes(gamma, fill = as.factor(topic))) +
  geom_histogram(alpha = 0.8, show.legend = FALSE) +
  facet_wrap(~ topic, ncol = 3) +
  labs(title = "Distribution of document probabilities for each topic",
       subtitle = "ENTER",
       y = "ENTER", x = expression(gamma))



# topic label
labelTopics(poliblogPrevFit, n=10)
plot.STM(poliblogPrevFit, type = "summary")


##################################################################################
# plot.STMpermute: Plot an STM permutation test (date x retweet) ----------
# https://github.com/mikajoh/tidystm
# https://github.com/cschwem2er/stminsights/blob/master/R/stm_effects.R
##################################################################################

#prep <- estimateEffect(1:50 ~ daterecode*retweet_1, poliblogPrevFit, meta)
prep_date <- estimateEffect(formula = 1:50 ~ retweet_1 + daterecode + retweet_1:daterecode,
                       stmobj = poliblogPrevFit,
                       metadata = meta)
#--------------------------------------------------------------------------
effect_date <- lapply(c(0, 1), function(i) {
  extract.estimateEffect(x = prep_date,
                         covariate = "daterecode", 
                         method = "continuous",
                         model = poliblogPrevFit, 
                         #labeltype = "frex", n = 4,
                         moderator = "retweet_1", 
                         moderator.value = i)})
effect_date <- do.call("rbind", effect_date)

#--------------------------------------------------------------------------
effect_date %>% filter(topic == 12) %>%
  ggplot(aes(x = covariate.value, y = estimate,
             #ggplot(effect, aes(x = covariate.value, y = estimate,
             ymin = ci.lower, ymax = ci.upper,
             group = moderator.value,
             fill = factor(moderator.value))) +
  scale_x_continuous(breaks=c(928,1125,10)) +
  facet_wrap(~ label, nrow = 5) +
  geom_ribbon(alpha = .5) +
  geom_line() +
  theme(plot.title = element_text(size = 18,
                                  family="Bahnschrift"),
        plot.subtitle = element_text(size = 12, family="Bahnschrift"),
        axis.text.x = element_text(angle=90, hjust=0.5, family="Bahnschrift"),
        axis.text.y = element_text(angle=0, hjust=0.5, family="Bahnschrift"),
        axis.title.x = element_text(angle=0, hjust=0.5, family="Bahnschrift"),
        axis.title.y = element_text(angle=90, hjust=0.5, family="Bahnschrift")) +
  labs(x = "Date",
       y = "Expected Proportion",
       title = "The changes in topic proportion over time",
       subtitle = "Original Tweets vs Retweets",
       fill = "Original:0, Retweets: 1") +
  theme(legend.position = "bottom", 
        legend.title=element_text(size=10, family="Bahnschrift"))



##################################################################################
# plot.STMpermute: Plot an STM permutation test (friend_1000 x retweet) ----------
##################################################################################

#prep <- estimateEffect(1:50 ~ friend_1000*retweet_1, poliblogPrevFit, meta)
prep_favorite <- estimateEffect(formula = 1:50 ~ retweet_1 + favorite_1000 + retweet_1:favorite_1000,
                              stmobj = poliblogPrevFit,
                              metadata = meta)
#--------------------------------------------------------------------------
effect_favorite <- lapply(c(0, 1), function(i) {
  extract.estimateEffect(x = prep_favorite,
                         covariate = "favorite_1000", 
                         method = "continuous",
                         model = poliblogPrevFit, 
                         #labeltype = "frex", n = 4,
                         moderator = "retweet_1", 
                         moderator.value = i)})
effect_favorite <- do.call("rbind", effect_favorite)
#--------------------------------------------------------------------------
retweet__favorite_inter_effects <- ggplot(effect_favorite, aes(x = covariate.value, y = estimate,
                                                          #ggplot(effect, aes(x = covariate.value, y = estimate,
                                                          ymin = ci.lower, ymax = ci.upper,
                                                          group = moderator.value,
                                                          fill = factor(moderator.value))) +
  facet_wrap(~ label, nrow = 5) +
  geom_ribbon(alpha = .5) +
  geom_line() +
  scale_x_continuous(labels = function(x) ifelse(x == 1, "1\nREP", ifelse(x == 0, "0\nDEM", x))) +
  theme(plot.title = element_text(size = 18,
                                  family="Bahnschrift"),
        plot.subtitle = element_text(size = 12, family="Bahnschrift"),
        axis.text.x = element_text(angle=90, hjust=0.5, family="Bahnschrift"),
        axis.text.y = element_text(angle=0, hjust=0.5, family="Bahnschrift"),
        axis.title.x = element_text(angle=0, hjust=0.5, family="Bahnschrift"),
        axis.title.y = element_text(angle=90, hjust=0.5, family="Bahnschrift")) +
  labs(x = "Favorite",
       y = "Expected Topic Proportion",
       title = "The number of favorite",
       subtitle = "Original tweets vs Retweets",
       fill = "Original:0, Retweets: 1") +
  theme(legend.position = "bottom", 
        legend.title=element_text(size=10, family="Bahnschrift"))
ggsave("retweet__favorite_inter_effects.png", plot = retweet__favorite_inter_effects, width = 30, height = 20, units = "cm")
#--------------------------------------------------------------------------
effect_favorite %>% filter(topic == 32) %>%
  ggplot(aes(x = covariate.value, y = estimate,
             #ggplot(effect, aes(x = covariate.value, y = estimate,
             ymin = ci.lower, ymax = ci.upper,
             group = moderator.value,
             fill = factor(moderator.value))) +
  facet_wrap(~ label, nrow = 5) +
  geom_ribbon(alpha = .5) +
  geom_line() +
  scale_x_continuous(labels = function(x) ifelse(x == 1, "1\nREP", ifelse(x == 0, "0\nDEM", x))) +
  theme(plot.title = element_text(size = 18,
                                  family="Bahnschrift"),
        plot.subtitle = element_text(size = 12, family="Bahnschrift"),
        axis.text.x = element_text(angle=90, hjust=0.5, family="Bahnschrift"),
        axis.text.y = element_text(angle=0, hjust=0.5, family="Bahnschrift"),
        axis.title.x = element_text(angle=0, hjust=0.5, family="Bahnschrift"),
        axis.title.y = element_text(angle=90, hjust=0.5, family="Bahnschrift")) +
  labs(x = "Favorite",
       y = "Expected Topic Proportion",
       title = "Topic proportion by the number of favorite",
       subtitle = "Original tweets vs Retweets",
       fill = "Original:0, Retweets: 1") +
  theme(legend.position = "bottom", 
        legend.title=element_text(size=10, family="Bahnschrift"))


save.image(file="appebee_50_all.RData")